- hosts: all
  become: true
  become_method: sudo

  tasks:

  #Istall rpm repository

  - name: install repository
    dnf:
      name: '{{item}}'
      state: installed
    with_items:
      - "https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm"
    when: "'zabbix_agents' in group_names"

  #Intall Agent

  - name: install zabbix agent
    dnf:
      name: '{{item}}'
      state: installed
    with_items:
      - zabbix-agent
    when: "'zabbix_agents' in group_names"

   #Create config file for zabbix agent

  - name: Create zabbix .conf file
    template:
      src: zabbix-agent-config.j2
      dest: /etc/zabbix/zabbix_agentd.conf
      force: yes
    when: "'zabbix_agents' in group_names"

  #Add firewall rules

  - name: add active ports
    firewalld:
      port: 10050-10051/tcp
      permanent: true
      state: enabled

  #Reload firewall

  - name: Reload service firewalld, in all cases
    ansible.builtin.systemd:
      name: firewalld
      state: reloaded

  #Starting and enabling zabbix server

  - name: enable service zabbix-server
    ansible.builtin.systemd:
      name: zabbix-agent
      state: started
      enabled: yes

